"""Original interior colors. Names are descriptive, not a paint brand's fan deck."""

from __future__ import annotations

COLORS: list[dict[str, str]] = [
    {"id": "clouded-linen", "name": "Clouded Linen", "hex": "#F3F0E8", "family": "White"},
    {"id": "milk-glass", "name": "Milk Glass", "hex": "#F7F6F2", "family": "White"},
    {"id": "soft-plaster", "name": "Soft Plaster", "hex": "#EFEAE2", "family": "White"},
    {"id": "paper-white", "name": "Paper White", "hex": "#F4F1EA", "family": "White"},
    {"id": "warm-cotton", "name": "Warm Cotton", "hex": "#F6F1E7", "family": "White"},
    {"id": "shell", "name": "Shell", "hex": "#F3EEE6", "family": "White"},
    {"id": "frost", "name": "Frost", "hex": "#EEF2F1", "family": "White"},
    {"id": "white-clay", "name": "White Clay", "hex": "#E7E2D8", "family": "White"},
    {"id": "oak-mist", "name": "Oak Mist", "hex": "#D9CDBF", "family": "Neutral"},
    {"id": "stone-hearth", "name": "Stone Hearth", "hex": "#C8B8A2", "family": "Neutral"},
    {"id": "greige-veil", "name": "Greige Veil", "hex": "#C9C2B4", "family": "Neutral"},
    {"id": "sandbar", "name": "Sandbar", "hex": "#D8CBB8", "family": "Neutral"},
    {"id": "biscuit", "name": "Biscuit", "hex": "#E4D5C3", "family": "Neutral"},
    {"id": "taupe-wash", "name": "Taupe Wash", "hex": "#B7A898", "family": "Neutral"},
    {"id": "mushroom", "name": "Mushroom", "hex": "#A89888", "family": "Neutral"},
    {"id": "camel-cloth", "name": "Camel Cloth", "hex": "#C4A882", "family": "Neutral"},
    {"id": "pale-slate", "name": "Pale Slate", "hex": "#D5D8D6", "family": "Gray"},
    {"id": "silver-birch", "name": "Silver Birch", "hex": "#C5C8C4", "family": "Gray"},
    {"id": "dove", "name": "Dove", "hex": "#B7B3AE", "family": "Gray"},
    {"id": "pewter", "name": "Pewter", "hex": "#9AA09C", "family": "Gray"},
    {"id": "harbor-gray", "name": "Harbor Gray", "hex": "#8E979B", "family": "Gray"},
    {"id": "storm", "name": "Storm", "hex": "#7E868A", "family": "Gray"},
    {"id": "graphite-mist", "name": "Graphite Mist", "hex": "#6E7370", "family": "Gray"},
    {"id": "iron", "name": "Iron", "hex": "#5C6164", "family": "Gray"},
    {"id": "still-water", "name": "Still Water", "hex": "#C5D5D6", "family": "Blue"},
    {"id": "powder-blue", "name": "Powder Blue", "hex": "#C9D6E3", "family": "Blue"},
    {"id": "sea-glass", "name": "Sea Glass", "hex": "#A9C4C4", "family": "Blue"},
    {"id": "quiet-tide", "name": "Quiet Tide", "hex": "#8AA8B5", "family": "Blue"},
    {"id": "delft-air", "name": "Delft Air", "hex": "#9BB0C4", "family": "Blue"},
    {"id": "north-sea", "name": "North Sea", "hex": "#5E7C8A", "family": "Blue"},
    {"id": "ink-blue", "name": "Ink Blue", "hex": "#2F4A5C", "family": "Blue"},
    {"id": "evening-navy", "name": "Evening Navy", "hex": "#243044", "family": "Blue"},
    {"id": "sage-milk", "name": "Sage Milk", "hex": "#D5DDD2", "family": "Green"},
    {"id": "mint-plaster", "name": "Mint Plaster", "hex": "#D7E3D8", "family": "Green"},
    {"id": "pale-celery", "name": "Pale Celery", "hex": "#E3E6C8", "family": "Green"},
    {"id": "olive-branch", "name": "Olive Branch", "hex": "#A3AA8C", "family": "Green"},
    {"id": "moss", "name": "Moss", "hex": "#7C8A4E", "family": "Green"},
    {"id": "fern-shadow", "name": "Fern Shadow", "hex": "#6E7F62", "family": "Green"},
    {"id": "greenhouse", "name": "Greenhouse", "hex": "#4F6B52", "family": "Green"},
    {"id": "deep-evergreen", "name": "Deep Evergreen", "hex": "#2F4638", "family": "Green"},
    {"id": "wheat-field", "name": "Wheat Field", "hex": "#E2C48A", "family": "Earth"},
    {"id": "honey-oak", "name": "Honey Oak", "hex": "#C9956A", "family": "Earth"},
    {"id": "copper-blush", "name": "Copper Blush", "hex": "#C48B74", "family": "Earth"},
    {"id": "clay-pot", "name": "Clay Pot", "hex": "#C47A5A", "family": "Earth"},
    {"id": "adobe", "name": "Adobe", "hex": "#A66B4F", "family": "Earth"},
    {"id": "terracotta-tile", "name": "Terracotta Tile", "hex": "#B85C38", "family": "Earth"},
    {"id": "canyon", "name": "Canyon", "hex": "#8C4A32", "family": "Earth"},
    {"id": "brown-study", "name": "Brown Study", "hex": "#6B4A36", "family": "Earth"},
    {"id": "pale-petal", "name": "Pale Petal", "hex": "#F0DDD8", "family": "Pink"},
    {"id": "blush-wall", "name": "Blush Wall", "hex": "#E7C8C4", "family": "Pink"},
    {"id": "peony", "name": "Peony", "hex": "#D4A0A8", "family": "Pink"},
    {"id": "dusty-rose", "name": "Dusty Rose", "hex": "#C98B8B", "family": "Pink"},
    {"id": "mauve-clay", "name": "Mauve Clay", "hex": "#B5898E", "family": "Pink"},
    {"id": "wine-stain", "name": "Wine Stain", "hex": "#6E3A42", "family": "Pink"},
    {"id": "cream-yellow", "name": "Cream Yellow", "hex": "#F6E7C1", "family": "Yellow"},
    {"id": "buttercream", "name": "Buttercream", "hex": "#F3E6C4", "family": "Yellow"},
    {"id": "pale-gold", "name": "Pale Gold", "hex": "#E6D3A1", "family": "Yellow"},
    {"id": "marigold-wash", "name": "Marigold Wash", "hex": "#E2B86A", "family": "Yellow"},
    {"id": "antique-gold", "name": "Antique Gold", "hex": "#C6A15B", "family": "Yellow"},
    {"id": "lacquer-red", "name": "Lacquer Red", "hex": "#8E2F2F", "family": "Bold"},
    {"id": "emerald", "name": "Emerald", "hex": "#1F6A4A", "family": "Bold"},
    {"id": "cobalt", "name": "Cobalt", "hex": "#2A4E8C", "family": "Bold"},
    {"id": "mustard", "name": "Mustard", "hex": "#C4922A", "family": "Bold"},
    {"id": "aubergine", "name": "Aubergine", "hex": "#5C3A55", "family": "Bold"},
    {"id": "teal-room", "name": "Teal Room", "hex": "#1F6A6A", "family": "Bold"},
    {"id": "espresso", "name": "Espresso", "hex": "#3B2A22", "family": "Dark"},
    {"id": "charred-wood", "name": "Charred Wood", "hex": "#3A312C", "family": "Dark"},
    {"id": "midnight", "name": "Midnight", "hex": "#1B2430", "family": "Dark"},
    {"id": "soft-black", "name": "Soft Black", "hex": "#2B2B2B", "family": "Dark"},
    {"id": "lamp-black", "name": "Lamp Black", "hex": "#1A1A1A", "family": "Dark"},
]

FAMILIES: list[str] = []
for _color in COLORS:
    if _color["family"] not in FAMILIES:
        FAMILIES.append(_color["family"])
